# .github/workflows/ci.yml

name: CI

on:
push:
branches: \[main]
pull\_request:

jobs:
test:
runs-on: ubuntu-latest
steps:
\- uses: actions/checkout\@v3

```
  - name: Fetch data on runner
    run: chmod +x fetch_data.sh && ./fetch_data.sh

  - name: Build Docker image
    run: docker build -t photon_env:ci .

  - name: Test in Docker: mtheory_r4_fit.py
    run: docker run --rm photon_env:ci python scripts/mtheory_r4_fit.py -N 16 -d 5 -t 1e-2

  - name: Test in Docker: scan_hidden_photon_refined_pickle.py
    run: docker run --rm -v "${{ github.workspace }}/DH_data:/app/DH_data" photon_env:ci python scripts/scan_hidden_photon_refined_pickle.py

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: "3.10"

  - name: Install Python dependencies
    run: pip install sympy pint emcee arviz rebound toml

  - name: Test locally: mtheory_r4_fit.py
    run: python scripts/mtheory_r4_fit.py -N 16 -d 5 -t 1e-2

  - name: Build & test Lean proofs
    uses: leanprover/lean-action@v1
```
