name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-python:
    name: Run Python Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check small data files
        run: |
          missing=false
          [ ! -f DH_data/std_soln_He.p ] && echo "::error::Missing DH_data/std_soln_He.p" && missing=true
          [ ! -d rotmod_files ] && echo "::error::Missing rotmod_files/" && missing=true
          $missing && echo "Please download archives from Zenodo" && exit 1
      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - run: |
          pip install --upgrade pip
          pip install sympy pint emcee arviz rebound toml h5py pandas
      - run: |
          python scripts/mtheory_r4_fit.py -N 16 -d 5 -t 1e-2
          python scripts/scan_hidden_photon_refined_pickle.py

  build-lean:
    name: Build & Verify Lean
    needs: test-python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Elan
        run: |
          curl -sSf https://elan.lean-lang.org/elan-init.sh | sh      # 官方推荐安装脚本【:contentReference[oaicite:5]{index=5}】
      - name: Verify Lean
        run: lean --version                                         # 确保已安装 Lean 4
      - name: Compile with lean --make
        working-directory: photon_project_formal
        run: lean --make src/Main.lean                             # 直接编译，不依赖 Lake【】
