name: CI

on:
  push:    {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 拉取数据到 runner（非 Docker）
        - name: Fetch data on runner (to file)
        run: |
         chmod +x fetch_data.sh
         mkdir -p logs
         # 把下载和解压日志都重定向到 logs/fetch.log
         bash fetch_data.sh > logs/fetch.log 2>&1 || (echo "Fetch failed, see logs/fetch.log" && cat logs/fetch.log && exit 1)


      # 3. 设置 Python 环境并安装依赖
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install sympy pint emcee arviz rebound toml

      # 4. 运行核心脚本测试
      - name: Test mtheory_r4_fit.py
        run: python scripts/mtheory_r4_fit.py -N 16 -d 5 -t 1e-2

      - name: Test scan_hidden_photon_refined_pickle.py
        run: python scripts/scan_hidden_photon_refined_pickle.py

      # 5. 形式化验证（Lean）
      - name: Build & test Lean proofs
        uses: leanprover/lean-action@v1
