# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库
      - uses: actions/checkout@v3

      # 2. 构建并运行 Docker 容器内的脚本测试
      - name: "Build Docker image"
        run: docker build -t photon_env:ci .

      - name: "Test in Docker: mtheory_r4_fit.py"
        run: docker run --rm photon_env:ci python scripts/mtheory_r4_fit.py -N 16 -d 5 -t 1e-2

      - name: "Test in Docker: scan_hidden_photon_refined_pickle.py"
        run: docker run --rm photon_env:ci python scripts/scan_hidden_photon_refined_pickle.py

      # 3. 主机环境下再跑一次 Python 测试（可选）
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: "Install Python dependencies"
        run: pip install sympy pint emcee arviz rebound

      - name: "Test locally: mtheory_r4_fit.py"
        run: python scripts/mtheory_r4_fit.py -N 16 -d 5 -t 1e-2

      # 4. 运行 Lean 形式化验证
      - name: "Build & test Lean proofs"
        uses: leanprover/lean-action@v1
