name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-python:
    name: Run Python Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- 不再自动下载大压缩包，只检查关键小文件存在性 ---
      - name: Check required small data files
        run: |
          missing=false
          for f in DH_data/std_soln_He.p rotmod_files/rotmod.dat; do
            if [ ! -f "$f" ]; then
              echo "::error::Required data file missing: $f"
              missing=true
            else
              echo "Found $f"
            fi
          done
          if [ "$missing" = true ]; then
            echo "Please download the full DH_data and rotmod_files archives from:" 
            echo "  https://your-storage.example.com/DH_data.rar"
            echo "  https://your-storage.example.com/rotmod_files.rar"
            echo "and extract them into the project root DH_data/ and rotmod_files/ directories."
            exit 1
          fi

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install sympy pint emcee arviz rebound toml h5py pandas

      - name: Run analysis scripts
        run: |
          python scripts/mtheory_r4_fit.py -N 16 -d 5 -t 1e-2
          python scripts/scan_hidden_photon_refined_pickle.py

  build-lean:
    name: Build & Verify Lean
    needs: test-python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Lean + Lake
        uses: leanprover/lean4-action@v1
        with:
          lean-version: latest

      - name: Verify Lake files
        working-directory: photon_project_formal
        run: |
          ls -l lakefile.toml lake-manifest.json lean-toolchain

      - name: Build Lean project
        working-directory: photon_project_formal
        run: lake build --verbose
