name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install sympy pint emcee arviz rebound toml h5py pandas

      - name: Download and verify external data
        run: |
          python scripts/fetch_data.py

      - name: Verify data exists
        run: |
          test -f data/DH_data/std_soln_He.p || (echo "::error::Missing std_soln_He.p"; exit 1)
          test -d data/rotmod_files || (echo "::error::Missing rotmod_files directory"; exit 1)

      - name: Run Python analysis
        run: |
          python scripts/mtheory_r4_fit.py -N 16 -d 5 -t 1e-2
          python scripts/scan_hidden_photon_refined_pickle.py

  build-lean:
    needs: test-python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Lean
        uses: leanprover/lean-action@v1
        with:
          toolchain: leanprover/lean4:v4.20.0
          cache: true

      - name: Download external data for Lean
        run: python scripts/fetch_data.py

      - name: Build with Lake
        run: lake build
