name: CI

on:
push: {}
pull\_request: {}

jobs:
test:
runs-on: ubuntu-latest
steps:
\- name: Checkout repository
uses: actions/checkout\@v3

```
  - name: Fetch data on runner
    run: |
      chmod +x fetch_data.sh
      ./fetch_data.sh

  - name: Build Docker image
    run: docker build -t photon_env:ci .

  - name: Test mtheory_r4_fit.py in Docker
    run: docker run --rm photon_env:ci python scripts/mtheory_r4_fit.py -N 16 -d 5 -t 1e-2

  - name: Test hidden photon scan in Docker
    run: docker run --rm -v "$GITHUB_WORKSPACE/DH_data:/app/DH_data" photon_env:ci python scripts/scan_hidden_photon_refined_pickle.py

  - name: Set up Python 3.10
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Install Python dependencies
    run: |
      pip install sympy pint emcee arviz rebound toml

  - name: Test mtheory_r4_fit.py locally
    run: python scripts/mtheory_r4_fit.py -N 16 -d 5 -t 1e-2

  - name: Build & test Lean proofs
    uses: leanprover/lean-action@v1
```
