name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-python:
    name: Run Python Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch required data
        run: |
          chmod +x fetch_data.sh
          bash fetch_data.sh

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install sympy pint emcee arviz rebound toml

      - name: Run analysis scripts
        run: |
          python scripts/mtheory_r4_fit.py -N 16 -d 5 -t 1e-2
          python scripts/scan_hidden_photon_refined_pickle.py

  build-lean:
    name: Build & Verify Lean
    needs: test-python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Lean + Lake
        uses: leanprover/lean4-action@v1
        with:
          lean-version: latest

      - name: Verify Lake files
        working-directory: photon_project_formal
        run: |
          ls -l lakefile.toml
          ls -l lake-manifest.json
          ls -l lean-toolchain

      - name: Build Lean project
        working-directory: photon_project_formal
        run: lake build --verbose
