name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # ————————————————————————————————————————————————
  # 1. Python 分析脚本测试
  test-python:
    name: Run Python Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug list files
        run: |
          echo "PWD=$(pwd)"
          echo "=== Repository Contents ==="
          ls -R .

      - name: Check required small data files
        shell: bash
        run: |
          # 定位仓库根目录
          REPOROOT="$(git rev-parse --show-toplevel)"
          echo "Repo root is $REPOROOT"
          missing=false

          # 检查单个文件和目录
          for P in \
            "$REPOROOT/DH_data/std_soln_He.p" \
            "$REPOROOT/rotmod_files"; do
            if [ ! -e "$P" ]; then
              echo "::error::Missing required path: $P"
              missing=true
            else
              echo "Found: $P"
            fi
          done

          if [ "$missing" = true ]; then
            echo "Please download and extract archives to DH_data/ and rotmod_files/:"
            echo "  https://zenodo.org/records/15691765/files/DH_data.rar?download=1"
            echo "  https://zenodo.org/records/15691753/files/rotmod_files.rar?download=1"
            exit 1
          fi

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install sympy pint emcee arviz rebound toml h5py pandas

      - name: Run analysis scripts
        run: |
          python scripts/mtheory_r4_fit.py -N 16 -d 5 -t 1e-2
          python scripts/scan_hidden_photon_refined_pickle.py

  # ————————————————————————————————————————————————
  # 2. Lean 源码编译测试
  build-lean:
    name: Build & Verify Lean
    needs: test-python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Elan (Lean toolchain manager)
        shell: bash
        run: |
          # 安装 Elan 并自动同意
          curl -sSf https://elan.lean-lang.org/elan-init.sh \
            | sh -s -- -y --default-toolchain leanprover/lean4:stable
          # 将 Elan 安装目录加入 PATH
          export PATH="$HOME/.elan/bin:$PATH"
          # 验证 lean 可用
          lean --version

      - name: Compile Lean sources with lean --make
        shell: bash
        working-directory: photon_project_formal
        run: |
          # 保证 lean 在 PATH 中
          export PATH="$HOME/.elan/bin:$PATH"
          lean --make src/Main.lean
